### PR TITLE
Weather app by Rohit

### PR DESCRIPTION
**Pull request by rtewari056**
A simple, weather app written in HTML, CSS, and JavaScript. It gathers data from OpenWeatherMap, via their public API.

### CODE REVIEW

**Comment by rtewari056** [comment]
@sudip-mondal-2002 will my projects count toward hacktoberfest? (sorry, I am new)

**Comment by sudip-mondal-2002** [comment]
If you contribute to a participating repository, yes it'll count

**Comment by rtewari056** [comment]
Is it a participating repository?

**Comment by sudip-mondal-2002** [comment]
Yes, this is participating

**Comment by rtewari056** [comment]
Okay. Thank you for merging my PR.

**Pull request merged**
